[package]
name = "static_variables"
version = "0.1.0"
authors = ["klose911 <klose911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
