kind: Pod
apiVersion: v1
metadata:
  name: secret-ssh-pod
  labels:
    name: secret-ssh
spec:
  volumes:
  - name: secret-volume
    secret:
      secretName: ssh-key-secret
  containers:
  - name: ssh-ssh-container
    image: redis
    volumeMounts:
    - name: secret-volume
      readOnly: true
      mountPath: "/etc/secret-volume"
